apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: motd-api-binding
  namespace: motd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: motd-api-role
subjects:
- kind: ServiceAccount
  name: motd-api